Repository Tutor2Tutee/T2T-GO, pull requests merged in 2021-11, with the labels that each got.

#17 Added Quizzes API
  controllers/init.go
  controllers/quizzes.go
  models/quizzes.go
  routers/quizzes.go
  routers/routes.go
Labels: Database, Backend

#10 added .idea folder
  .idea/.gitignore
  .idea/T2T-GO.iml
  .idea/modules.xml
  .idea/vcs.xml
Labels: documentation, Backend

#19 Fixed minor issues
  controllers/class.go
  controllers/quizzes.go
  controllers/user.go
  models/class.go
  models/quizzes.go
  models/user.go
Labels: Backend

#21 End to End Testing with In-Memory MongoDB Server
  controllers/class.go
  controllers/init.go
  db/db.go
  e2e_test.go
  go.mod
  go.sum
  main.go
  routers/classes.go
  routers/routes.go
Labels: Backend, TESTING

#20 JWT Implementation
  controllers/quizzes.go
  controllers/refresh_token.go
  controllers/user.go
  go.mod
  go.sum
  helpers/tokenHelper.go
  middlewares/jwt_auth.go
  models/user.go
  routers/refresh_token.go
  routers/routes.go
Labels: Backend

#23 Migrated to golang-jwt
  controllers/refresh_token.go
  go.mod
  go.sum
  helpers/tokenHelper.go
  middlewares/jwt_auth.go
Labels: Backend

#25 Split repository folder
  controllers/class.go
  controllers/init.go
  controllers/quizzes.go
  controllers/user.go
  e2e_test.go
  repository/README.md
  repository/classRepository.go
  repository/init.go
  repository/quizRepository.go
  repository/userRepository.go
  routers/classes.go
  routers/routes.go
  tests/mockDatabase.go
Labels: Database, Backend

#26 Implemented `JWT` authorization to api endpoints
  README.md
  assets/header.png
  controllers/class.go
  controllers/quizzes.go
  controllers/user.go
  go.mod
  go.sum
  header.jpeg
  helpers/tokenHelper.go
  models/quizzes.go
  models/user.go
  repository/README.md
  repository/quizRepository.go
  routers/classes.go
  routers/quizzes.go
  routers/user.go
Labels: enhancement, Backend
